kind: Deployment
apiVersion: apps/v1
metadata:
  name: assessment-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment
  template:
    metadata:
      labels:
        app: assessment
    spec:
      restartPolicy: Always
      serviceAccountName: xv-assessment-sa
      imagePullSecrets:
        - name: github-image-puller
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: container
          command:
            - /bin/bash
            - '-c'
            - '--'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'ghcr.io/crossvale-inc/assessment-alpha:v0.3'
          args:
            - while true; do sleep 30; done;
      serviceAccount: xv-assessment-sa
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600